# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedTweetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitID', models.IntegerField()),
                ('label', models.CharField(choices=[('pos', 'Positive'), ('neg', 'Negative'), ('neutral', 'Neutral')], max_length=15)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('time', models.CharField(max_length=200)),
                ('prob_pos', models.FloatField()),
                ('prob_neg', models.FloatField()),
                ('prob_neu', models.FloatField()),
            ],
        ),
    ]
