# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedtweetmodel',
            name='search_string',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='analyzedtweetmodel',
            name='label',
            field=models.CharField(choices=[('pos', 'Positive'), ('neg', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=15),
        ),
        migrations.AlterField(
            model_name='analyzedtweetmodel',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analyzedtweetmodel',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analyzedtweetmodel',
            name='prob_neg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analyzedtweetmodel',
            name='prob_neu',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analyzedtweetmodel',
            name='prob_pos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analyzedtweetmodel',
            name='time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='analyzedtweetmodel',
            name='twitID',
            field=models.IntegerField(default=0),
        ),
    ]
