# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetanalysis', '0002_auto_20170205_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedtweetmodel',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
    ]
